### ISSUE TITLE
MISSING FILES

### ISSUE THREAD

**Issue by CarlRonquillo** [yireo/Yireo_NextGenImages#1]
Class Yireo\NextGenImages\Image\UrlReplacer does not exist
Class Yireo\Webp2\Browser\BrowserSupport does not exist (got this file from the release 7.7 version)

**Comment by jissereitsma** [comment]
Thanks for reporting this and sorry for the mess. Could you see if version 0.0.4 is now fixing things for you?

**Comment by CarlRonquillo** [comment]
Thank you for responding.

Unfortunately, now this classes is missing.
Class Yireo\Webp2\Browser\BrowserSupport does not exist
Class Yireo\Webp2\Image\UrlReplacer does not exist

**Comment by jissereitsma** [comment]
@CarlRonquillo Could you mention your versions of both the WebP 2 module (which should be 0.9.2) and the NextGenImages module (which should be 0.0.4)?

**Comment by CarlRonquillo** [comment]
Yes that's the versions I'm using.
I install it via composer.

**Comment by jissereitsma** [comment]
Thanks. Could you copy and paste the output of the following commands here in this issue?
```bash
composer show | grep yireo
grep -r Browser vendor/yireo/magento2-next-gen-images
grep -r Browser vendor/yireo/magento2-webp2
```

**Comment by CarlRonquillo** [comment]
![image](https://user-images.githubusercontent.com/11956545/100969804-a96b7a80-356e-11eb-8291-027996c36000.png)

Please note that I made it work, by copying some of the files from your webp2 8.0 release.

**Comment by jissereitsma** [comment]
Thanks. But we might be troubleshooting an old issue. Could you try upgrading to WebP2 version 0.9.3 and NextGenImages 0.0.4?

**Comment by CarlRonquillo** [comment]
OK i'll try.

**Comment by CarlRonquillo** [comment]
![image](https://user-images.githubusercontent.com/11956545/100973318-4f21e800-3575-11eb-8dbd-fc79dfb37ed7.png)

still got this issue on your latest versions

**Comment by jissereitsma** [comment]
I'm noticing something that I overlooked before: Are you sure that you are making use of composer? Because a simple `composer update` will update all files to their latest version. Because composer takes care of dependency loading, I definitely can not recommend not to use composer. The error deals with a file in `app/code` in a namespace `Nineteen02`?

**Comment by CarlRonquillo** [comment]
Yes, I've used composer in installing your modules. But the App/code/Nineteen02 that you are seeing is just my rewrite for the module.

If you look closely to your repository, you cannot see any Browser directory. It's really missing

![image](https://user-images.githubusercontent.com/11956545/100981271-8d250900-3581-11eb-8261-9cbb4cd5e741.png)

**Comment by CarlRonquillo** [comment]
Or do you change it to Yireo_NextGenImages/Browser ?

**Comment by CarlRonquillo** [comment]
![image](https://user-images.githubusercontent.com/11956545/100981987-7cc15e00-3582-11eb-8fda-b5b3e8b80a3b.png)

**Comment by jissereitsma** [comment]
Yes, there have been many changes in both extensions. I would not recommend you to build your extension on top of this, because there are no API extension points (service contracts, events, etcetera). What is the reason you have built your extension on top of this?

My first goal would be to see if the Yireo extension works for you or not. Let's close that issue afterwards. And then let's open a new issue on how you can create a new extension on top of Yireo WebP2.

**Comment by jissereitsma** [comment]
I'm closing this now because of inactivity, and because no one else run into issues with newer releases. Feel free to re-open if this same issue is still bugging.
