### ISSUE TITLE
when i install the module in code folder then i am facing  issue

### ISSUE THREAD

**Issue by moazzama** [yireo/Yireo_NextGenImages#12]
Error: Class 'WebPConvert\WebPConvert' not found in /home/httpd/wpcholz/wpcholz.de/public_html/app/code/Yireo/Webp2/Image/ConvertWrapper.php:37 Stack trace: #0
https://wpcholz.de/

**Comment by jissereitsma** [comment]
So how did you install the dependencies? Please note that if you are **not** understanding the question on how dependencies and you do not know how to solve this issue, then you should not go for an advanced installation method, but use composer instead. Not using composer is **not** making it easier, contrary to what you think.

I will close this ticket because it seems you are not using composer, while that's the only supportable way of installing this extension.

**Comment by moazzama** [comment]
Hi,
you can see the i have installed both extension in our folder
![error](https://user-images.githubusercontent.com/68050583/130322095-4a042cfb-d5e4-4666-bf85-df4960f9beb7.PNG)

**Comment by jissereitsma** [comment]
You are not getting the point. The error message you are seeing is complaining about yet another extension. If you want to pick up on this and keep installing this in `app/code`, then study the `composer.json` files of all packages involved and install all (!) dependencies mentioned in the `require` section. 

If you are not understanding this error (and you are clearly not), then do **NOT** (please understand that the bold letters are for a clear reason) follow the procedure. But instead use `composer`. If you are unable to use `composer`, fix that problem first. Anyone with Magento is using `composer`, so are you not doing that? Composer is meant to fix problems like this.

This will be my last message here. You are stating that you want to install into `app/code` because you apparently do not want to use composer. My statement here is: You are encountering issues that are not easy at all - this disproves your point. Using composer is the only way to go for. If you are not understanding this, most likely you do not understand what composer is actually about - dependency management. You and I are **not** going to manage dependencies and spent further time on this - instead, composer is going to manage this for us.

**Comment by moazzama** [comment]
Thanks for this information
