### ISSUE TITLE
Webp conversion on category pages

### ISSUE THREAD

**Issue by RickvanB** [yireo/Yireo_NextGenImages#37]
Hi,

I've been looking through the code, but I don't think it's possible to convert jpg/png images on the category overview pages?
Is this something that's still on the roadmap or easy to implement by myself?

Thanks in advance.

**Comment by jissereitsma** [comment]
I'm a bit confused. The module does not do anything specific on category pages and in all of the environments I have seen so far, category pages contain images that are properly converted. Which code did you go through to make you make such a conclusion? Could it be that you are trying to address a specific issue in a specific environment that you are customizing?

**Comment by RickvanB** [comment]
Hi @jissereitsma,

We are working on performance improvements and we noticed that images on category/POP pages are not converted. I looked at the code and came to that initial conclusion. Is it also possible to do convert images via the pagebuilder?

**Comment by jissereitsma** [comment]
If you could point me to the code that you think is causing issues, please do. But as of yet, there is no specific issue reported by you, so I'm unable to be of use.

As for PageBuilder, no there is no ability to convert images. That's also not needed. PageBuilder simply spits out HTML & CSS. That HTML & CSS could contain `img` tags. Those `img` tags are then converted by this extension. If the conversion is not done, let's talk about that specific HTML.

**Comment by jissereitsma** [comment]
You are asking about things but running in circles: Yes, the module is replacing images in any type of HTML on any type of page, regardless of the content. There are no exceptions for whatever you name as blocks, widgets and CMS-pages: Those are just backend concepts that are generating HTML. This extension does not care about the backend concepts, it cares about the HTML.

I'm going to keep my eye off of this topic for a while, because it seems that either I would jump to the rescue and start thinking along the lines of fixing the project, or you need to come up with details. Without details, there is nothing I can do.

What is the HTML? Show me the code. Let's not talk in theory. Let's talk code.

Disable the Mageplaza module.

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity.
