### ISSUE TITLE
"Class `Yireo\NextGenImages\Config\Config` does not exist"

### ISSUE THREAD

**Issue by lewisje** [yireo/Yireo_NextGenImages#59]
I tried updating this module to 0.3.16 and I got the following error after running `php bin/magento setup:upgrade`:

> Class Yireo\NextGenImages\Config\Config does not exist

Additionally, I got this error:

> In Config.php line 31:
>  syntax error, unexpected 'DirectoryList' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

I do not have this problem when updating to 0.3.15; before today, it was at an earlier version.

I also had this problem when updating from 0.3.15 to 0.3.16.

I am running PHP 7.3.33, in case that matters; also, I see that there have been only two commits since 0.3.15, and one of them changed the `Yireo\NextGenImages\Config\Config` class, by adding a `private` member of type `DirectoryList`: https://github.com/yireo/Yireo_NextGenImages/commit/671dabac5ac9f418ff5ae0a86cb8b2e31561c784

Maybe `DirectoryList` requires PHP 7.4+, although I haven't found anything about it in the manual.

**Comment by jissereitsma** [comment]
Thanks for addressing this. Even though I really really think that PHP 7.3 should not be used anymore and upgrading the PHP version is going to be so much more valuable than trying to upgrade an extension like this, still, this extension was supposed to support PHP 7.3 for the time being anyway. This is now fixed in version 0.3.17.

**Comment by lewisje** [comment]
Indeed, it was fixed.
